title: Geeknight Chennai
email: geeknight.chennai@thoughtworks.com
description: >
  An open forum for geeks to connect, discuss &amp; learn latest ideas, technologies and trends in software development.
baseurl: ""
url: ""

# Build settings
plugins_dir: ./_plugins
markdown: kramdown

port: 3000

sass:
    sass_dir: _sass

# Handling Reading
safe:                 false
include:              [".htaccess"]
exclude:              ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files:           [".git", ".svn"]
encoding:             "utf-8"
strict_front_matter: false

theme: minima

# Outputting
permalink:  :title
paginate_path: /page:num
timezone:      null