title: Geeknight Chennai
email: geeknight.chennai@thoughtworks.com
description: >
  An open forum for geeks to connect, discuss &amp; learn latest ideas, technologies and trends in software development.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

port: 3000

sass:
    sass_dir: _sass